### ISSUE TITLE
Player hand having invalid values. 

### ISSUE THREAD

**Issue by nikhilbaby** [danguilherme/uno#24] opened 2019-10-23 09:39 UTC
Please check the following image to find the issue:

![image](https://user-images.githubusercontent.com/9347673/67379568-bca7ca80-f5a6-11e9-821a-67ef1aa9d7e4.png)

In the image, it can be seen that a player has ` Card { _value: 12, _color: 4 }`. But if you check the colors enum you can see that there is no value for color 4.

How can I assign a color to the wild card where the color that I want is `4`?

**Comment by danguilherme** [comment] 2019-10-23 14:18
This is a duplicate of #15. Could you please replicate your problem there?

**Closed by danguilherme** 2019-10-23 14:18 UTC
